#!/bin/bash

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=5g
#SBATCH --time=00:10:00
#SBATCH --job-name=NanoPlot_Ada_Script_01
#SBATCH --output=/gpfs01/home/mxsh12/slurm-%x-%j.out
#SBATCH --error=/gpfs01/home/mxsh12/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxsh12@exmail.nottingham.ac.uk

# source your bash profile so you can use conda
source $HOME/.bash_profile

# activate conda environment
conda activate nanoplot_env

#definitions
wd=/share/BioinfMSc #root working directory
lrdir=$wd/Matt_resources/long_reads #path to long reads
srdir=$wd/Matt_resources/short_reads #path to short reads
gdir=$wd/rotation1/Group3 #path to group directory

#main body
NanoPlot --$gdir/merged_pass.fastq.gz -o $gdir/qc_check_pass
NanoPlot --$gdir/merged_fail.fastq.gz -o $gdir/qc_check_fail
NanoPlot --$gdir/merged_fail.fastq.gz -o $gdir/qc_check_all

# deactivate conda environment
conda deactivate